<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Arpit1-Joshi" name="com.lojack.qa.testcases.LoginTestCase" tests="8" failures="0" timestamp="01 Aug 2019 20:10:09 GMT" time="117.534" errors="2">
  <testcase name="loginPageTitleTest" time="16.093" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="loginPagelogoTest" time="13.331" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="blankLoginTest" time="12.702" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="incorrectUserLoginTest" time="14.293" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="incorrectPasswordLoginTest" time="13.576" classname="com.lojack.qa.testcases.LoginTestCase">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...Please check user...&gt; but was:&lt;... Invalid User ...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...Please check user...> but was:<... Invalid User ...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.lojack.qa.testcases.LoginTestCase.incorrectPasswordLoginTest(LoginTestCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- incorrectPasswordLoginTest -->
  <testcase name="blankUserLoginTest" time="13.373" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="blankPasswordLoginTest" time="16.859" classname="com.lojack.qa.testcases.LoginTestCase"/>
  <testcase name="correctcredentialsLoginTest" time="17.307" classname="com.lojack.qa.testcases.LoginTestCase">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...&gt; but was:&lt;...User/Dashboard.aspx&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<...User/Dashboard.aspx>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.lojack.qa.testcases.LoginTestCase.correctcredentialsLoginTest(LoginTestCase.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- correctcredentialsLoginTest -->
</testsuite> <!-- com.lojack.qa.testcases.LoginTestCase -->
